<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>4.0.0-alpha3</Version>
    <PackageDescription>Common code for use between APIs.</PackageDescription>
    <RepositoryUrl>https://github.com/NCIOCPL/NCI.OCPL.Api.Shared</RepositoryUrl>
    <Authors>National Cancer Institute - Office of Communications and Public Liaison</Authors>
  </PropertyGroup>

  <ItemGroup>

    <!-- Explicit framework reference because this project builds a library to support APIs, not the actual APIs.-->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <!-- Elasticsearch doesn't strictly follow semantic versioning; the client MUST
          be locked to the same version as the server. -->
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.19.12" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.6.*" />
  </ItemGroup>
</Project>